# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Setup JFrog CLI
      # You may pin to the exact commit or the version.
      # uses: jfrog/setup-jfrog-cli@fed9c975cc3a21f4d98015b9ef6369201b2d5ca4
      uses: jfrog/setup-jfrog-cli@v1.1.0
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
    - run: jfrog --version
    - run: jfrog rt u * pypi-local
